Xian55/WowClassicGrindBot

Libs/NativeMethods.cs
with no full screen.
Currently only 100% windows GUI scale supported.
=> Add Support for running the game client with windowed

Libs/WowProcess.cs
Adding Wow Classic PRT to the list of processes the server recognizes.
=> Added wow classic ptr string to process name list

Libs/Goals/ApproachTargetGoal.cs, Libs/Goals/CastingHandler.cs, Libs/Goals/GoapGoal.cs, Libs/Goals/LastTargetLoot.cs, Libs/Goals/LootGoal.cs, Libs/Goals/ParallelGoal.cs, Libs/Goals/SkinningGoal.cs
When a mob dies the last used ability most likely forces to wait a full GCD time(1.5s) don't do that! 
Wait the least amount of time instead.
Approximately best case scenario 15x speed gain. Reducing the mob kill awareness to 100ms from 1.5s
However its more around 300-700ms.
=> Dont wait full GCD upon mob kill

Core/Addon/LevelTracker.cs, Json/WorldToMap/WorldMapArea.json
1) mobs killed bug - compared the mobs killed now with in game addon(FarmingNotes) for a few days, it's working correctly now
2) worldmaparea.json update, to correct MapIds per https://wowpedia.fandom.com/wiki/UiMapID/Classic
=> Two bugs fixed

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, Core/Addon/BuffStatus.cs, Core/Addon/PlayerBitValues.cs, Core/Addon/SpellInRange.cs, Core/Requirement/RequirementFactory.cs, Json/class/Shaman_1.json, Json/class/Shaman_2.json, README.md
Addon: Added necessary range and buff tracking in order to work with the
approach and pull goal. For Rockbiter it was necessary to poll the
GetWeaponEnchantInfo API to get know about the uptime. This one handy
for rogue poisons, blacksmith sharpening stones as well.
RequirementFactory: has two new req to keep track HasMainHandEnchant and
HasOffHandEnchant.
=> Class Support: Shaman

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, BlazorServer/Pages/BotHeader.razor, Core/Bag/BagReader.cs
Also show at the header how much available slot we have
=> fix: Make sure to query the last container bag :dense:

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, Core/Bag/BagReader.cs
=> More tightly pack the bagslot count

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, Core/Addon/PlayerReader.cs, Core/Requirement/RequirementFactory.cs, Json/class/Warlock_20.json, Json/class/Warlock_20_shard_farm.json, Json/class/Warlock_26_Immunity.json, README.md
Show the usage in warlock profiles
=> Addon: Retrive PetHealth as percentage

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, Core/ClassConfig/KeyAction.cs, Core/Requirement/RequirementFactory.cs
Addon: used an old api - does not reported correctly the actionbarslot spell usable
KeyAction: make sure the "WhenUsable" is overridable
=> Fix: KeyAction.WhenUsable

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, Core/Addon/PlayerReader.cs
Add timer for when was the loot window last opened.
=> Add Timer based events

BlazorServer/Shared/NavMenu.razor, BlazorServer/wwwroot/css/site.css
=> Collapsable navbar text

BlazorServer/Pages/RouteComponent.razor, BlazorServer/Pages/_Host.cshtml
=> dark grid route components

Core/Goals/GoalThread.cs, Core/Goals/GoapGoal.cs, Core/Goals/LootGoal.cs, Core/Goals/SkinningGoal.cs
The mentioned issue stuck issue also appears when pulling enemy npc during executing the Loot and Skinning Goal.
Even though the Goal preconditions has been negated to exit the current goal. It still keep remaining 🤷
=> GoapGoal: new concept Repeatable

Core/Goals/ConsumeCorpse.cs, Core/Goals/LootGoal.cs, Core/Goals/SkinningGoal.cs
Problems: 
- as a ranged if you have killed the mob too far away sometimes didn't waited properly for both of the Goals.
- skinning many times finished prematurely
=> Cleanup and rethink the loot and skin goals

PathingAPI/Controllers/PPatherController.cs, PathingAPI/Search/PPatherService.cs
=> Add ability to draw a path from coordinates

Core/Addon/SpellInRange.cs, Json/class/Paladin_1.json
Judgement learned only in level 4
before that no way to tell when to stop since tbc
=> fix paladin low level combat range condition

BlazorServer/Startup.cs, BlazorServer/appsettings.json, Core/Configuration/StartupConfigPathing.cs, Core/PPather/Client/AnTcpClient.cs, Core/PPather/Objects/AnTcpResponse.cs, Core/PPather/RemotePathingAPIV3.cs
RemoteV2 no longer continued, the map dependencies are out of date. If you have the supported(v13) map files you can still use it.
However above >15 it is required to use V3. Performance wise should be the same. However the Server has been rewritten in purely c++.
[Server](https://github.com/Xian55/AmeisenNavigation/tree/feature/guess-z-coord-after-rewrite)
=> Added RemoteV3 pathing client.

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, Addons/DataToColor/Query.lua, Core/Actionbar/ActionBarBitStatus.cs, Core/Actionbar/ActionBarCurrentAction.cs, Core/Addon/PlayerReader.cs, Core/Goals/CastingHandler.cs, Core/Requirement/RequirementFactory.cs
CastingHandler: Takes advantage of CurrentAction API.
Can wait for pre queued actions, such as Heroic Strike, Raptor Strike those kinds abilities which were consumed in the next auto attack! 
On the other hand it solves the latency between the client and the server.
Possible the final piece of the CastingHandler rework. :pray:
=> Feature/actionbar usable  current action

BlazorServer/run.bat, PathingAPI/run.bat
That should make life easier. Anyway, it seems that the skinning part does not work very well, and there's no option to specify a "background" mode. Are there any plans on these two features?
=> Use run.bat path as working directory

Addons/DataToColor/DataToColor.lua, Addons/DataToColor/DataToColor.toc, SharedLib/DataFrameConfig/DataFrameConfiguration.cs, SharedLib/DataFrameConfig/DataFrameMeta.cs
Goal: For the future where more than 100 frames are needed :sweat:
=> Feature: Add support for multi row setup

BlazorServer.Test/BlazorServer.Test.csproj, BlazorServer/BlazorServer.csproj, BlazorServer/FrameConfigurator.cs, BlazorServer/Pages/MiniMapComponent.razor, BlazorServer/Pages/ProfileSelectorComponent.razor, BlazorServer/Pages/RecordPath.razor, BlazorServer/PathingApi/LocalPathingApi.cs, Core/ClassConfig/KeyAction.cs, Core/Core.csproj, Core/PPather/RemotePathingAPIV3.cs, CoreTests/CoreTests.csproj, PathingAPI/Controllers/PPatherController.cs, PathingAPI/PPather/Graph/GraphChunk.cs, PathingAPI/PPather/Graph/PathGraph.cs, PathingAPI/PPather/Graph/Spot.cs, PathingAPI/PPather/Triangles/ChunkedTriangleCollection.cs, PathingAPI/PPather/Triangles/MPQTriangleSupplier.cs, PathingAPI/PPather/Triangles/TriangleCollection.cs, PathingAPI/PPather/Triangles/TriangleMatrix.cs, PathingAPI/PPather/Triangles/Utils.cs, PathingAPI/PPather/Triangles/WmoFile.cs, PathingAPI/PathingAPI.csproj, PathingAPI/Search/PPatherService.cs, README.md, Server/Server.csproj, SharedLib/SharedLib.csproj, WinAPI/WinAPI.csproj
* Updated the project to `.net5`
* Updated the projects 3rd party dependencies to comply `.net5`
* Minor warning fixes about `CA1805`
* Minor warning fixes about `CA1806`
* Set `BlazorServer` and `PathingAPI` projects `PlatformTarget` to `x86`
* Updated `Readme.md` about the changes
=> Migrate project to .net5

Core/Goals/AdhocGoal.cs, Core/Goals/AdhocNPCGoal.cs, Core/Goals/ApproachTargetGoal.cs, Core/Goals/CombatGoal.cs, Core/Goals/FollowRouteGoal.cs, Core/Goals/GoalFactory.cs, Core/Goals/MountHandler.cs, Core/Goals/ParallelGoal.cs, Core/Goals/PullTargetGoal.cs, Json/class/Druid_30_cat_bear.json
* `MountHandler`: take care of mount up and dismount in every goal from now on. Considering `Travel Form` as well.
* Added `Druid_30_cat_bear` profile which contains the required logic to benefit Travel Form while `FollowRouteGoal` is active.
=> Feature: Add support for Travel Form during `FollowRouteGoal`

Core/BotController.cs, Core/ClassConfig/ClassConfiguration.cs, Core/Requirement/RequirementFactory.cs, Json/class/Warlock_1.json, Json/class/Warlock_10.json, Json/class/Warlock_20.json, Json/class/Warlock_20_shard_farm.json, Json/class/Warlock_26_Immunity.json, Json/class/Warlock_4.json, Json/class/Warlock_8.json, README.md
* Format all `Warlock` profiles
* Demonstrate user defined variable in `Warlock` profiles
=> Feature: Ability to create user defined variables in `ClassConfig`

Core/BotController.cs, Core/ClassConfig/ClassConfiguration.cs, Core/Goals/AdhocNPCGoal.cs, Core/Goals/ApproachTargetGoal.cs, Core/Goals/CastingHandler.cs, Core/Goals/CorpseRunGoal.cs, Core/Goals/FollowRouteGoal.cs, Core/Goals/PullTargetGoal.cs, Core/Goals/StopMoving.cs, Core/Goals/WalkToCorpseGoal.cs, Core/Goals/WrongZoneGoal.cs, Core/Input/ConfigurableInput.cs, Core/Path/PlayerDirection.cs, Core/Path/StuckDetector.cs, Json/class/Paladin_20.json, Json/class/Warrior_1_MovementKeys.json, README.md
* Added the ability to change the default movement keys - arrows  - to any keys like `WASD`
* Added example profile Warror_1_MovementKeys as example
* StopMoving: Using `ValueTask` instead of `Task`
=> Feature: Configurable movement keys

Core/Goals/AdhocNPCGoal.cs, Core/Goals/FollowRouteGoal.cs, Core/Path/PlayerDirection.cs, Game/Input/IInput.cs, Game/Input/InputSimulator.cs, Game/Input/InputWindowsNative.cs, Game/Input/WowProcessInput.cs
* Input: Introduce a new KeyPressNoDelay api. Where there will be no extra random delay, just the specified milliseconds. On top of this when `KeyPress` logs the amount of time now considers the random delay and returns the total amount of time spent.
* Core: Refactor `PlayerDirection`. No longer blocks the current Thread with Sleep. Rather using Task + Task.Delay to implement waiting mechanism. On the other hand uses `KeyPressNoDelay` so truly only presses the button for the calculated duration based on `TurnAmount` -> `TurnDuration`.
* Core: adjust distances in FollowPath goal behaviors
=> Feature: improve navigation turn input

BlazorServer/LoggerSink.cs, BlazorServer/Pages/GoalsComponent.razor, BlazorServer/Pages/GoapGoalView.razor, BlazorServer/Pages/LogComponent.razor, Core/ClassConfig/ClassConfiguration.cs, Core/ClassConfig/KeyAction.cs, Core/Goals/CastingHandler.cs, Core/Goals/MountHandler.cs, Json/class/Warrior_20.json, Json/class/Warrior_24.json, README.md
* Remove runtime check from `CastIfReady()` regarding `KeyAction.ConseleKey`
* `CastingHandler` remove `PressCastKeyAndWaitForCastToEnd()`
* `CastingHandler`: Split `CastIfReady()` into `CanRun()` and `Cast()`
* `CastingHandler`: `Cast()` only check `Form` requirement when its needed
* `CastingHandler`: `Cast()` Remove duplicate `GCD` wait when switching from `Shoot` to any spell.
* `CastingHandler`: `WaitForGCD()` move condition outside.
* `CastingHandler`: `SwitchForm()` no longer handles `Form` condition existence and same `Form`.
* `KeyAction`: Get rid of try catch blocks. Simplyfiy `LastClicked` related calls.
* `MountHandler`: Druid switches `Travel_Form` incase its mentioned in `ClassConfig`. Otherwise uses normal mount.
* `CastingHandler`: `SwitchForm()` better condition for …
=> Feature: improve CastingHandler + ClassConfig + KeyAction / Frontend changes

BlazorServer/Pages/ScreenshotComponent.razor, Core/BotController.cs, Game/WoWScreen/WowScreen.cs, SharedLib/NpcFinder/NpcNameFinder.cs
* ScreenshotCompontent: Clicking on the live preview toggles the visibility
=> Feature: Toggle Screenshot thread

Core/Addon/AddonDataProvider/AddonDataProvider.cs, Core/Addon/AddonDataProvider/IAddonDataProvider.cs, Game/WoWScreen/WowScreen.cs, SharedLib/DirectBitmap/DirectBitmapCapturer.cs, SharedLib/DirectBitmap/IBitmapProvider.cs, SharedLib/DirectBitmap/IDirectBitmapProvider.cs, SharedLib/NpcFinder/LineOfNpcName.cs, SharedLib/NpcFinder/NpcNameFinder.cs, SharedLib/NpcFinder/NpcPosition.cs, SharedLib/SharedLib.csproj
* Better resource management by locking the Bitmap data while it has been used for reading the pixel data. On the other hand making AddonData more read friendly.
* `NpcNameFinder`: better resource management. Only locking the BitmapData while its being accessed for read. Using structs instead of classes.
* `SharedLib`: Allow unsafe code
As a result 
* Less likely to trigger Garbage Collection
* Global memory usage has been reduced by 100-150 mb
=> Feature: better bitmap handling

Addons/DataToColor/Constants.lua, Addons/DataToColor/DataToColor.toc, Addons/DataToColor/Query.lua, Addons/DataToColor/Versions.lua, Addons/DataToColor/embeds.xml, Addons/DataToColor/libs/LibClassicCasterino/LibClassicCasterino.lua
=> Added `LibClassicCasterino` to polyfill target `UnitCastingInfo` and `UnitChannelInfo` for SoM

Addons/DataToColor/DataToColor.toc, Addons/DataToColor/Storage.lua, Core/AddonComponent/BuffStatus.cs, Core/Requirement/RequirementFactory.cs, Json/class/Hunter_1.json, Json/class/Hunter_10.json, Json/class/Hunter_18.json, Json/class/Hunter_26.json, Json/class/Hunter_30.json, Json/class/Hunter_4.json, Json/class/Hunter_6.json, Json/class/Hunter_62.json, Json/class/Hunter_66.json, README.md
* Keep track of `Aspect of the Viper`
* Tidy up all hunter profiles
* Added `Hunter_66` profile using `Kill Command` and `Aspect of the Viper`. Pretty mana conservative.
=> Refactor: Hunter `"Aspect of"`

Core/Database/WorldMapAreaDB.cs, Core/PPather/RemotePathingAPIV3.cs, README.md, SharedLib/Data/WorldMapAreaFactory.cs
* The server will transform back to the original coordinate system to match the input. 
* Avoid allocating new list of `WorldMapArea`. 
* The api changed. Its uses the default `PATH` to take advantage interpolation or smoothing.
=> Feature: improve remote pathing v3

BlazorServer/Pages/BotHeader.razor, Core/Addon/ConfigAddonReader.cs, Core/Addon/IAddonReader.cs, Core/Addon/SpellBookReader.cs, Core/Bag/BagReader.cs, Core/Talents/TalentReader.cs
* Currently known spells from spellbook count 
* Spent talent points. 
* Player health and current resource both numeric and percentage
* At the top shows up the Race and class
=> Frontend: BotHeader component shows more info about the status of the initial obtaining process.

BlazorServer.Test/BlazorServer.Test.csproj, BlazorServer/BlazorServer.csproj, BlazorServer/LoggerSink.cs, BlazorServer/Pages/LogComponent.razor, BlazorServer/Pages/RouteComponent.razor, Core/Core.csproj, Core/Path/RouteInfo.cs, CoreTests/CoreTests.csproj, Game/Game.csproj, PathingAPI/PPather/Graph/PathGraph.cs, PathingAPI/PathingAPI.csproj, README.md, Server/Server.csproj
* Converted all projects to `dotnet6.0` which were previously used `dotnet5.0`
* Updated 3rd party packages
* Clean the whole solution
* Delete every project `bin` and `obj` folders in order to avoid cached build!
=> Upgrade: dotnet6.0

Core/Addon/AddonReader.cs, Core/Addon/SquareReader.cs, Core/AddonComponent/CreatureRecord.cs, Core/AddonComponent/LevelTracker.cs, Core/Bag/BagItem.cs, Core/Blacklist/Blacklist.cs, Core/BotController.cs, Core/ClassConfig/ClassConfiguration.cs, Core/ClassConfig/KeyAction.cs, Core/Core.csproj, Core/GOAP/GoapAgent.cs, Core/GOAP/GoapAgentState.cs, Core/Goals/FollowRouteGoal.cs, Core/Goals/GoalFactory.cs, Core/Goals/TargetLastDeadGoal.cs, Core/Goals/WalkToCorpseGoal.cs, Core/Gossip/GossipReader.cs, Core/MiniMapNodeAlert/MinimapNodeFinder.cs, Core/PPather/RemotePathingAPI.cs, Core/Path/PlayerDirection.cs, Core/Path/RouteInfo.cs, Core/Requirement/RequirementFactory.cs, DataConfig/DataConfig.csproj, Game/Game.csproj, SharedLib/SharedLib.csproj, WinAPI/WinAPI.csproj, WowheadDB/WowheadDB.csproj
* Warnings which prevents creating a build
=> Upgrade: `netstandard2.1` projects to `dotnet6.0`

Core/Goals/FollowRouteGoal.cs
* Make the movement less twitchy. 
* Only `AdjustHeading` once per frame. 
* Respect `shouldMount` from the get go. 
* Less likely stuck in unstuck mode.
* Improved logging
* Don't attempt to mount up if happen to have target in prior
=> Feature: FollowRouteGoal improvements

BlazorServer/Pages/MiniMapComponent.razor, Core/Actionbar/ActionBarCooldownReader.cs, Core/Addon/AddonReader.cs, Core/AddonComponent/CreatureHistory.cs, Core/AddonComponent/CreatureRecord.cs, Core/AddonComponent/LevelTracker.cs, Core/AddonComponent/RecordInt.cs, Core/Bag/BagItem.cs, Core/Bag/BagReader.cs, Core/BotController.cs, Core/ClassConfig/KeyAction.cs, Core/Goals/AdhocGoal.cs, Core/Goals/ApproachTargetGoal.cs, Core/Goals/CombatGoal.cs, Core/Goals/CorpseRunGoal.cs, Core/Goals/Navigation.cs, Core/Goals/ParallelGoal.cs, Core/Goals/PullTargetGoal.cs, Core/Goals/Wait.cs, Core/Goals/WrongZoneGoal.cs, Core/Gossip/GossipReader.cs, Core/Path/PlayerDirection.cs, Core/Path/StuckDetector.cs, Game/WoWScreen/ScreenChangeEventArgs.cs, PathingAPI/PPather/Triangles/TriangleMatrix.cs, PathingAPI/Search/Search.cs, SharedLib/NpcFinder/NpcNameFinder.cs
Where the time needed to show to the end user can use `ToLocalTime()`.
=> Replace `DateTime.Now` with `DateTime.UtcNow` internally.
