- WinAPI/NativeMethods.cs
- WinAPI/WinAPI.csproj
fix: use GetDeviceCaps to find out system dpi instead of GetDpiForSystem so backward compatible til windows 2k
> Obtain DPI using w2k api

- Core/Addon/AddonDataProvider/AddonDataProvider.cs
when the meta colors(begin and end) is exists.
Possibly filtering out some of the strange cases when the target guid or
id is not reported properly.
> AddonDataProvider: Make sure to only grab the data

- BlazorServer/Pages/FrameConfiguration.razor
- Server/Program.cs
- SharedLib/DataFrameConfig/DataFrameMeta.cs
At 1440p resolution estimating the required bitmap sample size was not correct.
with the given configuration:
- size: 1
- spacing: 1
- rows: 1
with the given formula under estimate the required width
```
var size = new SizeF(frames * (this.size + spacing), rows * (this.size + spacing));
```
the possible bitmap width with 100 frames supposed to be around ~200px in width with 1:1 ratio. 
However given the fact how `uiScale` works, just rather avoid to calculate the required width.
> fix: 1440p resolution wrong estimation of possible required bitmap width

- Core/Addon/PlayerReader.cs
Issue:
Either on low(<30) or high(>100) framerate, the loot and skinning Goals failing when the player has to move to the corpse in prior to start the actions.
The problem, no sync between the in-game and backend update loop, and many times things not happened in the right order or some of the placed `WaitForNUpdate` not waited for an in-game redraw(`onUpdate`) as intended.
Example:
In-Game:
> Mob dies
> npc name found and right click happened
> the player starts moving in the game
Backend:
> based on the playerReader, the player stays still, by prematurely evaluating `CombatUtil.IsPlayerMoving` => false
Note: `GlobalTime` max value is 2^24. so it can overflow with the current setup every 7.8 hours. To mitigate the issue using a different way to calculate time frame differences in …
> Backend relies on the in game onUpdate tick when it comes to WaitForNUpdate

- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/EventHandlers.lua
- Core/Addon/UI_ERROR.cs
- Core/Goals/CastingHandler.cs
- Core/Goals/CombatGoal.cs
- Core/Goals/PullTargetGoal.cs
Addon: Some of the important casting error were hidden behind the `ERR_SPELL_FAILED_S`.
To be useful, now the addon will show `ERR_BADATTACKFACING` and one new error after keypress.
- "SPELL_FAILED_MOVING", --6 "Can't do that while moving";
With that in mind reworked the `CastingHandler`.
before setting a KeyAction, resetting the `playerReader.LastUIErrorMessage` so after the keypress can check immediately if there was an issue by checking `playerReader.LastUIErrorMessage`. and given the known issues can react to put the player character back in action.
Also with verbose logging made more clear, what reaction going to be executed.
> Rework casting handler and react to LastUIErrorMessage

- Core/Goals/CastingHandler.cs
- Core/Goals/CombatGoal.cs
Goal:
- To make it more consistent and detect errors and more reliable
- Take advantage of the recently gained performance upgrades
About the old system:
- Upon having an issue there was no reaction to it
- Inconsistent behavior with the instant and castbar based abilities. Such as handling `DelayAfterCast`, Retry if failed.
- Loosely defined actions, there were no feedback from the game after each action
To solve the following issues. Extracted the three main logics from `CastIfReady`
- `PressKeyAction` - always resets the `playerReader.LastUIErrorMessage` that way can check later, after the keypress was successful what result it game in game.
-  `CastInstant` - Handles those abilties which don't have `HasCastbar` attribute.
-  `CastCastbar` - Handles the other side when castbar is …
> Rework how the CastingHandler components works internally.

- BlazorServer/AddonConfigurator.cs
Based on the documentation, the server gets started from the start.bat file, which changes the directory to "BlazorServer". (which is the same when it is running from VS)
In that case "./Addon/" folder is not valid, however the exception handling is basically useless because the GetVersion returns null, instead of an exception.
So the fix is basically solves the fallback branch of the version check.
> Fix installed addon version check

- Addons/DataToColor/DataToColor.lua
- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/EventHandlers.lua
- Addons/DataToColor/Storage.lua
- Core/Addon/AddonReader.cs
- Core/BotController.cs
- Core/Goals/AdhocNPCGoal.cs
- Core/Goals/GoalFactory.cs
- Core/Gossip/GossipReader.cs
Added support for obtaining the available Gossip options upon interacting with an NPC. Which opens up the possibility to handle other types of gossip options.
`AdhocNPCGoal`: incase the merchant option is gated behind a gossip option pick that and start the selling process.
On the other hand Addon is now picking the lowest key from the `stack` to have some order. It's required for the `GossipReader` to work properly.
> Add support for gossip based vendoring

- Core/Goals/CorpseConsumed.cs
- Core/Goals/FollowRouteGoal.cs
- Core/Goals/LootGoal.cs
- Core/Goals/SkinningGoal.cs
After killing a multiple or single mob during combat don't wait for losing combat because depending on the server backend and the client-server communication this could take up a lot of time doing nothing.
> Instead of 'incombat' GoapKey use 'dangercombat'

- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/Query.lua
Goal: `UnitCastingInfo` and `UnitChannelInfo` used different version of the API. Missing `Interruptable` flag.
> Addon Fix: UnitCastingInfo and UnitChannelInfo different classic to tbcc

- Addons/DataToColor/DataToColor.lua
- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/EventHandlers.lua
- Core/AddonComponent/CreatureHistory.cs
Bump Addon version to `1.1.47`
> Fix: Damage taken guid was unable to expire due `LastEvent` kept renewing

- Core/Requirement/RequirementFactory.cs
- Json/class/Warlock_10.json
- Json/class/Warlock_20.json
- Json/class/Warlock_20_shard_farm.json
- Json/class/Warlock_26_Immunity.json
- README.md
* Added `TargetsMe` condition
* Added `TargetsPet` condition
* Added `TargetsNone` condition
* Demonstrate `Targets*` condition in Warlock profiles. Only use `Shadow Bolt` when somebody else tanking the target.
> Feature: Expose `TargetTargetEnum`

- Core/Goals/TargetPetTarget.cs
* `TargetPetTarget`: Gives much better result. Increase the chance to loot the corpse. Only triggers if multiple enemies appears in the combat.
> Fix: TargetPetTarget goal use `dangercombat` key instead of pure `incombat`. 

- Json/class/Druid_20_cat_bear.json
- Json/class/Druid_24_cat_bear.json
- Json/class/Druid_30_cat_bear.json
* Fixed an issue with moonfire pull while closing the gap from the target in the very last moment shifts out from cat and does a moonfire.
* Fixed a typo in `Json/class/Druid_30_cat_bear.json`
> Fix: Druid moonfire pull + typo

- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/Versions.lua
Tested on: 
* Classic TBC 2.5.3.41812
* Classic Era 1.14.2.41858
> Fix: `UnitCastingInfo` and `UnitChannelInfo` for _classic_. Also for _classic_era_

- AddonConfig/AddonConfig.csproj
- Game/Input/InputWindowsNative.cs
- MasterOfPuppets.sln
- SharedLib/Data/Creature.cs
- SharedLib/Data/EntityId.cs
- SharedLib/Data/Item.cs
- SharedLib/Data/Spell.cs
- SharedLib/Data/TalentTab.cs
- SharedLib/Data/TalentTreeElement.cs
- SharedLib/Data/WorldMapArea.cs
- Utilities/ImageFilter/ImageFilter/ImageFilter.csproj
- Utilities/ImageFilter/ImageFilter/MainWindow.xaml.cs
- Utilities/PathMaker/PathMaker/PathMaker.csproj
- Utilities/ReadDBC_CSV/ConsumablesExtractor.cs
- Utilities/ReadDBC_CSV/Extractor/CSVExtractor.cs
- Utilities/ReadDBC_CSV/ItemExtractor.cs
- Utilities/ReadDBC_CSV/ReadDBC_CSV.csproj
- Utilities/ReadDBC_CSV/SpellExtractor.cs
- Utilities/ReadDBC_CSV/TalentExtractor.cs
- Utilities/ReadDBC_CSV/WorldMapAreaExtractor.cs
- Utilities/ReadItems/ConsoleApp10/ReadWowDb.csproj
- Utilities/WowheadDB_Extractor/PerZoneSkinnable.cs
- Utilities/WowheadDB_Extractor/WowheadDB_Extractor.csproj
- Utilities/WowheadDB_Extractor/ZoneExtractor.cs
* Every project is converted either from `dotnetstandard2.1` or `dotnet3.1` or `dotnet5.0` to `dotnet6.0`
* Removed every reference of the old `dotnetstandard2.1` builds
* Utility projects are also upgraded
* The main solution requires Visual Studio 2022 from now on
* `SharedLib` based data structures are `readonly struct`s
* Some places replaced logging with the `LoggerMessage` generated version. Console output colorful 🤸‍♂️ 
* Build times significantly faster
* Runtime memory usage significantly reduced. From around ~150mb can go below 100mb
> Upgrade: every poject to `dotnet6.0`

- PathingAPI/PPather/Triangles/MPQTriangleSupplier.cs
- PathingAPI/PPather/Triangles/StormDll.cs
- PathingAPI/PPather/Triangles/WmoFile.cs
* Don't use exceptions for EOF :dense:
* Don't try to parse that long MPQ file list, just read the `DataConfig.MPQ` dictionary to see what exists
* Log less about PPather pathfinding and asset loading process
> Feature: PPather less exception and logging

- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/Query.lua
Having macro like this which requires an item in inventory and have to use it on a weapon and maybe have to accept a prompt.
```lua
#showtooltip
/use Solid Sharpening Stone
/use 16
/click StaticPopup1Button1
```
The macro always show up as `Usable` even if the mentioned item `Solid Sharpening Stone` is missing from inventory. 
Incase the Actionbarslot icon is show up as red question mark that means the macro item is missing from the inventory or the macro has no assigned icon. 
That means all macros required to have any icon beside the default. This can be solved by adding the `#showtooltip` in the first line.
> Fix: macro which contains items shows up always usable even when the item dosen't exists in inventory

- Addons/DataToColor/DataToColor.lua
- Addons/DataToColor/DataToColor.toc
- Addons/DataToColor/EventHandlers.lua
- BlazorServer/Pages/BagItemComponent.razor
- BlazorServer/Pages/BotHeader.razor
- BlazorServer/Pages/Money.razor
- BlazorServer/Pages/Swag.razor
- BlazorServer/WApi.cs
- Core/Addon/EquipmentReader.cs
- Core/Bag/Bag.cs
- Core/Bag/BagItem.cs
- Core/Bag/BagReader.cs
* Addon: Listen for swap/equip/unequip bags
* Addon: instead of using a baked `21` bagslot count use the related api
* Frontend: Added a `WApi` class to hold wowhead related endpoints
* Frontend: `BagReader` listen for equipmentchange and so be aware of the bag related changes.
* Frontend: BagItemComp: has the ability to show the item icon also using better name colors.
* Frontend: Swag: Container names shows up. Change the order of bag and inventory display. Temporary the equipments shows up here.
* Core: `BagReader`: Fix an issue when swapping bags which has less amount of BagSlots then the prior one.
> Feature: Swagger overhaul

- Core/Goals/GoalFactory.cs
- Core/Goals/LootGoal.cs
- Core/Goals/PostKillLootGoal.cs
**Issue:** Sometimes when pulling multiple mobs in a combat the character keep facing to the latest enemy. And therefor the previously killed mobs getting out of player vision.
**Solution:** Take advantage of the approximated kill locations. When no npcname is visible, turn the closest one and try to find again.
> Core: LootGoal: Take advantage of the known corpse locations when no npcname was visible.

- Core/BotController.cs
- Core/ClassConfig/KeyAction.cs
- Core/Goals/CastingHandler.cs
- Core/Requirement/RequirementFactory.cs
- Json/class/Druid_1.json
- Json/class/Druid_10_bear.json
- Json/class/Druid_12_bear.json
- Json/class/Druid_14_bear.json
- Json/class/Druid_16_bear.json
- Json/class/Druid_20_cat_bear.json
- Json/class/Druid_24_cat_bear.json
- Json/class/Druid_32_cat_bear.json
- Json/class/Druid_4.json
- Json/class/Druid_6.json
- Json/class/Druid_bear.json
- Json/class/Druid_cat.json
- Json/class/Paladin_10.json
- Json/class/Paladin_16.json
- Json/class/Paladin_20.json
- Json/class/Paladin_30.json
- Json/class/Paladin_4.json
- Json/class/Paladin_6.json
- Json/class/Paladin_8.json
- Json/class/Rogue_12.json
- Json/class/Warrior_10.json
- Json/class/Warrior_12.json
- Json/class/Warrior_20.json
- Json/class/Warrior_24.json
- README.md
* [Core: KeyAction.CastIfAddsVisible has been removed and replaced with Requirement of 'AddVisible'](https://github.com/Xian55/WowClassicGrindBot/commit/01e59135bf7b20e8990ad4cd10e7a4a437d03aab) 
* [Core: RequirementFactory: Upon 'WhenUsable' is enabled. Check the in-game cooldown existence and the actionbar usable api as well.](https://github.com/Xian55/WowClassicGrindBot/commit/c2b0369879b1fee4b764ad301e7c7a2e4f5678b5)
* [Druid Profiles: Update all of them to current standard. Format docs. Moonfire based pull uses 'AddVisible' requirement. AdhocGoals no longer needed to be guarded with 'AfterCastWaitBuff' and 'DelayAfterCast'. 'Cooldown' mostly removed.](https://github.com/Xian55/WowClassicGrindBot/commit/eca3e3bb8053aa9ae8897a1e50b27918861fd097)
* [Profiles: Replace 'CastIfAddsVisible' …
> Refactor: `KeyAction.CastIfAddsVisible` replaced with `AddsVisible`. Requirement `CD==0` replaced by `WhenUsable`

- BlazorServer/PathingApi/LocalPathingApi.cs
- Core/Goals/AdhocGoal.cs
- Core/Goals/AdhocNPCGoal.cs
- Core/Goals/FollowRouteGoal.cs
- Core/Goals/GoalFactory.cs
- Core/Goals/GoalThread.cs
- Core/Goals/Navigation.cs
- Core/Goals/WalkToCorpseGoal.cs
- Core/Input/ConfigurableInput.cs
- Core/PPather/IPPather.cs
- Core/PPather/RemotePathingAPI.cs
- Core/PPather/RemotePathingAPIV3.cs
- Game/Input/WowProcessInput.cs
- PathingAPI/Data/DummyVector3.cs
- PathingAPI/Data/Lines.cs
- PathingAPI/Data/Sphere.cs
* Cleanup the `PPather` related codebase
* `Navigation` pathfinding has been delegated to a worker thread. No longer blocks the bot thread.
* `Navigation` path result can be discarded incase the component no longer active.
* `RemotePathingV1`: `System.Numerics.Vector3` were not serialized properly.
* `AdhocNPCGoals`: when route keep getting added after reinitializing `ClassConfig`.
* `AdhocNpcGoal`: where the original path route modified after `Reverse`.
* `AdhocGoal`: regarding `Life tap` like spell unable to use more than 1 charge.
> Feature: nonblocking navigation - small fixes
